### ISSUE TITLE
Embedded binaries

### ISSUE THREAD

**Issue by staff0rd** [sheldonth/ios-cmake#3]
I'm linking to frameworks in `CMakeLists.txt` like this;

```
# To link a .framework framework from the filesystem
target_link_libraries(${APP_NAME} 
  ${PROJECT_SOURCE_DIR}/Carthage/Build/iOS/GCDWebServers.framework
)
```

Compilation succeeds, however I need the framework to additionally be added to Embedded Binaries for deployment.  Do you know if its possible to do that via cmake?

**Comment by sheldonth** [comment]
The CMake in this project defines a macro for you, called `COPY_TO_BUNDLE`

Using it should result in your framework being in the bundle -- however it will also probably get you into rpath hell, because the framework will be in a different location relative to the exectuable than when it was compiled, so when the dynamic linker goes to open it there will be trouble. I'd suggest adding a small python/coffeescript script to your program to call out to the `install_name_tool` executable on Mac to fix this. I wish there was a nice compact CMake solution, but I haven't seen one yet.

**Comment by sheldonth** [comment]
Hey did you make any progress here? I noticed some of my cmake based apps are just including .frameworks without issue in the packaged output, so I actually think you shouldn't be encountering any problem at all.

**Comment by sheldonth** [comment]
Closing this issue since we now have code demonstrating the compilation of a dynamic framework and the inclusion of that dynamic framework in the app bundle to support a deployment.
